apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swinra-ingress
  namespace: swinra
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5m"
spec:
  ingressClassName: nginx
  rules:
    - host: swinra.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: swinra-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swinra-frontend
                port:
                  number: 80
